"""Adição das tabelas TipoVariacaoPalavra e VariacaoPalavra

Revision ID: 06dbd6aab507
Revises: 618b5e4292bb
Create Date: 2025-10-09 22:43:17.094159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06dbd6aab507'
down_revision: Union[str, Sequence[str], None] = '618b5e4292bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_variacao_palavra',
    sa.Column('id_tipo_variacao_palavra', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('descricao_tipo_variacao_palavra', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_variacao_palavra')
    )
    op.create_table('variacao_palavra',
    sa.Column('id_variacao_palavra', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_palavra', sa.Integer(), nullable=False),
    sa.Column('id_tipo_variacao_palavra', sa.Integer(), nullable=False),
    sa.Column('id_palavra_variacao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_palavra'], ['palavra.id_palavra'], ),
    sa.ForeignKeyConstraint(['id_palavra_variacao'], ['palavra.id_palavra'], ),
    sa.ForeignKeyConstraint(['id_tipo_variacao_palavra'], ['tipo_variacao_palavra.id_tipo_variacao_palavra'], ),
    sa.PrimaryKeyConstraint('id_variacao_palavra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variacao_palavra')
    op.drop_table('tipo_variacao_palavra')
    # ### end Alembic commands ###
