"""adição de novas tabelas auxiliares para  a IA

Revision ID: 09a5601caa42
Revises: 14d1fabd03ae
Create Date: 2026-01-12 09:24:12.785717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a5601caa42'
down_revision: Union[str, Sequence[str], None] = '14d1fabd03ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desabilita_fk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desabilita_fk',
    sa.Column('linhas_desabilitar_fk', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
