"""correção do idioma_materno

Revision ID: 14d1fabd03ae
Revises: 9130aa390f30
Create Date: 2025-11-28 19:52:06.287838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d1fabd03ae'
down_revision: Union[str, Sequence[str], None] = '9130aa390f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_idioma_materno', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('usuario_id_idiomamaterno_fkey'), 'usuario', type_='foreignkey')
    op.create_foreign_key(None, 'usuario', 'idioma', ['id_idioma_materno'], ['id_idioma'])
    op.drop_column('usuario', 'id_idiomamaterno')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_idiomamaterno', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuario', type_='foreignkey')
    op.create_foreign_key(op.f('usuario_id_idiomamaterno_fkey'), 'usuario', 'idioma', ['id_idiomamaterno'], ['id_idioma'])
    op.drop_column('usuario', 'id_idioma_materno')
    # ### end Alembic commands ###
