"""Aumentar campo senha para LargeBinary

Revision ID: 184df4292cbb
Revises: dc529628516e
Create Date: 2025-09-28 12:32:32.084255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184df4292cbb'
down_revision: Union[str, Sequence[str], None] = 'dc529628516e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE usuario
        ALTER COLUMN senha TYPE BYTEA
        USING senha::bytea;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE usuario
        ALTER COLUMN senha TYPE VARCHAR(255)
        USING encode(senha, 'escape');
    """)
    # ### end Alembic commands ###
