"""adição de nova coluna na questao_usuario

Revision ID: 49caa065793f
Revises: ded343944172
Create Date: 2025-11-22 19:58:24.231386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49caa065793f'
down_revision: Union[str, Sequence[str], None] = 'ded343944172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questao_usuario', sa.Column('resposta_usuario', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questao_usuario', 'resposta_usuario')
    # ### end Alembic commands ###
