"""Correção adicão tabelas auxiliares IA

Revision ID: 672db7fdb78c
Revises: 09a5601caa42
Create Date: 2026-01-14 16:32:01.125025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672db7fdb78c'
down_revision: Union[str, Sequence[str], None] = '09a5601caa42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questao_objetivo',
    sa.Column('id_questao_objetivo', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_questao', sa.Integer(), nullable=False),
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('qtq_palavras', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo.id_objetivo'], ),
    sa.ForeignKeyConstraint(['id_questao'], ['questao.id_questao'], ),
    sa.PrimaryKeyConstraint('id_questao_objetivo')
    )
    op.create_table('questao_palavra_cerf',
    sa.Column('id_questao_palavra_cerf', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_questao', sa.Integer(), nullable=False),
    sa.Column('A1', sa.Integer(), nullable=False),
    sa.Column('A2', sa.Integer(), nullable=False),
    sa.Column('B1', sa.Integer(), nullable=False),
    sa.Column('B2', sa.Integer(), nullable=False),
    sa.Column('C1', sa.Integer(), nullable=False),
    sa.Column('C2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_questao'], ['questao.id_questao'], ),
    sa.PrimaryKeyConstraint('id_questao_palavra_cerf')
    )
    op.create_table('usuario_acerto_cerf',
    sa.Column('id_usuario_acerto_cerf', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('A1', sa.Integer(), nullable=False),
    sa.Column('A2', sa.Integer(), nullable=False),
    sa.Column('B1', sa.Integer(), nullable=False),
    sa.Column('B2', sa.Integer(), nullable=False),
    sa.Column('C1', sa.Integer(), nullable=False),
    sa.Column('C2', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_acerto_cerf')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_acerto_cerf')
    op.drop_table('questao_palavra_cerf')
    op.drop_table('questao_objetivo')
    # ### end Alembic commands ###
