"""Adição da tabela usuario_token

Revision ID: 6c5a44b9c8ac
Revises: 184df4292cbb
Create Date: 2025-09-28 16:23:54.081964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5a44b9c8ac'
down_revision: Union[str, Sequence[str], None] = '184df4292cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_token',
    sa.Column('id_usuario_token', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_token')
    # ### end Alembic commands ###
