"""Criar tabelas iniciais

Revision ID: 770382e18466
Revises: 
Create Date: 2025-09-27 13:34:18.988402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770382e18466'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidade',
    sa.Column('iddisponibilidade', sa.Integer(), nullable=False),
    sa.Column('descricaodisponibilidade', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('iddisponibilidade')
    )
    op.create_table('experiencia_idioma',
    sa.Column('idexperienciaidioma', sa.Integer(), nullable=False),
    sa.Column('descricaoexperienciaidioma', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idexperienciaidioma')
    )
    op.create_table('idioma',
    sa.Column('ididioma', sa.Integer(), nullable=False),
    sa.Column('descricaoidioma', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ididioma')
    )
    op.create_table('objetivo',
    sa.Column('idobjetivo', sa.Integer(), nullable=False),
    sa.Column('descricaoobjetivo', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idobjetivo')
    )
    op.create_table('sexo',
    sa.Column('idsexo', sa.Integer(), nullable=False),
    sa.Column('descricaosexo', sa.String(length=20), nullable=False),
    sa.Column('siglasexo', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('idsexo')
    )
    op.create_table('tipo_questao',
    sa.Column('idtipoquestao', sa.Integer(), nullable=False),
    sa.Column('descricaotipoquestao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idtipoquestao')
    )
    op.create_table('questao',
    sa.Column('idquestao', sa.Integer(), nullable=False),
    sa.Column('json', sa.String(length=100), nullable=False),
    sa.Column('idobjetivo', sa.Integer(), nullable=False),
    sa.Column('idtipoquestao', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('caminhoarquivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['idobjetivo'], ['objetivo.idobjetivo'], ),
    sa.ForeignKeyConstraint(['idtipoquestao'], ['tipo_questao.idtipoquestao'], ),
    sa.PrimaryKeyConstraint('idquestao')
    )
    op.create_table('usuario',
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('datanascimento', sa.Date(), nullable=False),
    sa.Column('idsexo', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('iddisponibilidade', sa.Integer(), nullable=False),
    sa.Column('ididiomamaterno', sa.Integer(), nullable=False),
    sa.Column('cadastrocompleto', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('dataultimoacesso', sa.DateTime(), nullable=False),
    sa.Column('datacriacao', sa.DateTime(), nullable=False),
    sa.Column('dataexclusao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['iddisponibilidade'], ['disponibilidade.iddisponibilidade'], ),
    sa.ForeignKeyConstraint(['ididiomamaterno'], ['idioma.ididioma'], ),
    sa.ForeignKeyConstraint(['idsexo'], ['sexo.idsexo'], ),
    sa.PrimaryKeyConstraint('idusuario')
    )
    op.create_table('conjunto_questao',
    sa.Column('idconjuntoquestao', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('datacriacao', sa.DateTime(), nullable=False),
    sa.Column('dataconclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('idconjuntoquestao')
    )
    op.create_table('data_acesso',
    sa.Column('iddataacesso', sa.Integer(), nullable=False),
    sa.Column('dataacesso', sa.DateTime(), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('iddataacesso')
    )
    op.create_table('email_confirmacao',
    sa.Column('idemailconfirmacao', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('idemailconfirmacao')
    )
    op.create_table('experiencia_idioma_usuario',
    sa.Column('idexperienciaidiomausuario', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('ididioma', sa.Integer(), nullable=False),
    sa.Column('idexperienciaidioma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idexperienciaidioma'], ['experiencia_idioma.idexperienciaidioma'], ),
    sa.ForeignKeyConstraint(['ididioma'], ['idioma.ididioma'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('idexperienciaidiomausuario')
    )
    op.create_table('nivel_questao_usuario',
    sa.Column('idnivelquestaousuario', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('idquestao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idquestao'], ['questao.idquestao'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('idnivelquestaousuario')
    )
    op.create_table('objetivo_usuario',
    sa.Column('idobjetivousuario', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('idobjetivo', sa.Integer(), nullable=False),
    sa.Column('datacriacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('dataexclusao', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['idobjetivo'], ['objetivo.idobjetivo'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('idobjetivousuario')
    )
    op.create_table('questao_usuario',
    sa.Column('idquestaousuario', sa.Integer(), nullable=False),
    sa.Column('acerto', sa.Boolean(), nullable=True),
    sa.Column('dataacerto', sa.String(length=3), nullable=True),
    sa.Column('idquestao', sa.Integer(), nullable=False),
    sa.Column('idusuario', sa.Integer(), nullable=False),
    sa.Column('idconjuntoquestao', sa.Integer(), nullable=False),
    sa.Column('datacriacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idconjuntoquestao'], ['conjunto_questao.idconjuntoquestao'], ),
    sa.ForeignKeyConstraint(['idquestao'], ['questao.idquestao'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuario.idusuario'], ),
    sa.PrimaryKeyConstraint('idquestaousuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questao_usuario')
    op.drop_table('objetivo_usuario')
    op.drop_table('nivel_questao_usuario')
    op.drop_table('experiencia_idioma_usuario')
    op.drop_table('email_confirmacao')
    op.drop_table('data_acesso')
    op.drop_table('conjunto_questao')
    op.drop_table('usuario')
    op.drop_table('questao')
    op.drop_table('tipo_questao')
    op.drop_table('sexo')
    op.drop_table('objetivo')
    op.drop_table('idioma')
    op.drop_table('experiencia_idioma')
    op.drop_table('disponibilidade')
    # ### end Alembic commands ###
