"""Criar tabelas iniciais

Revision ID: 770382e18466
Revises: 
Create Date: 2025-09-27 13:34:18.988402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770382e18466'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidade',
    sa.Column('id_disponibilidade', sa.Integer(), nullable=False),
    sa.Column('descricao_disponibilidade', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_disponibilidade')
    )
    op.create_table('experiencia_idioma',
    sa.Column('id_experiencia_idioma', sa.Integer(), nullable=False),
    sa.Column('descricao_experiencia_idioma', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_experiencia_idioma')
    )
    op.create_table('idioma',
    sa.Column('id_idioma', sa.Integer(), nullable=False),
    sa.Column('descricao_idioma', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_idioma')
    )
    op.create_table('objetivo',
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('descricao_objetivo', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_objetivo')
    )
    op.create_table('sexo',
    sa.Column('id_sexo', sa.Integer(), nullable=False),
    sa.Column('descricao_sexo', sa.String(length=20), nullable=False),
    sa.Column('sigla_sexo', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id_sexo')
    )
    op.create_table('tipo_questao',
    sa.Column('id_tipo_questao', sa.Integer(), nullable=False),
    sa.Column('descricao_tipo_questao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_questao')
    )
    op.create_table('questao',
    sa.Column('id_questao', sa.Integer(), nullable=False),
    sa.Column('json', sa.String(length=100), nullable=False),
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('id_tipo_questao', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo.id_objetivo'], ),
    sa.ForeignKeyConstraint(['id_tipo_questao'], ['tipo_questao.id_tipo_questao'], ),
    sa.PrimaryKeyConstraint('id_questao')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('id_sexo', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('id_disponibilidade', sa.Integer(), nullable=False),
    sa.Column('id_idiomamaterno', sa.Integer(), nullable=False),
    sa.Column('cadastro_completo', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_ultimo_acesso', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_exclusao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_disponibilidade'], ['disponibilidade.id_disponibilidade'], ),
    sa.ForeignKeyConstraint(['id_idiomamaterno'], ['idioma.id_idioma'], ),
    sa.ForeignKeyConstraint(['id_sexo'], ['sexo.id_sexo'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('conjunto_questao',
    sa.Column('id_conjunto_questao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conjunto_questao')
    )
    op.create_table('data_acesso',
    sa.Column('id_data_acesso', sa.Integer(), nullable=False),
    sa.Column('data_acesso', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_data_acesso')
    )
    op.create_table('email_confirmacao',
    sa.Column('id_email_confirmacao', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_email_confirmacao')
    )
    op.create_table('experiencia_idioma_usuario',
    sa.Column('id_experiencia_idioma_usuario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_idioma', sa.Integer(), nullable=False),
    sa.Column('id_experiencia_idioma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_experiencia_idioma'], ['experiencia_idioma.id_experiencia_idioma'], ),
    sa.ForeignKeyConstraint(['id_idioma'], ['idioma.id_idioma'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_experiencia_idioma_usuario')
    )
    op.create_table('nivel_questao_usuario',
    sa.Column('id_nivel_questao_usuario', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_questao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_questao'], ['questao.id_questao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_nivel_questao_usuario')
    )
    op.create_table('objetivo_usuario',
    sa.Column('id_objetivo_usuario', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_exclusao', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo.id_objetivo'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_objetivo_usuario')
    )
    op.create_table('questao_usuario',
    sa.Column('id_questaousuario', sa.Integer(), nullable=False),
    sa.Column('acerto', sa.Boolean(), nullable=True),
    sa.Column('data_acerto', sa.String(length=3), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_conjunto_questao', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_conjunto_questao'], ['conjunto_questao.id_conjunto_questao'], ),
    sa.ForeignKeyConstraint(['id_questao'], ['questao.id_questao'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_questaousuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questao_usuario')
    op.drop_table('objetivo_usuario')
    op.drop_table('nivel_questao_usuario')
    op.drop_table('experiencia_idioma_usuario')
    op.drop_table('email_confirmacao')
    op.drop_table('data_acesso')
    op.drop_table('conjunto_questao')
    op.drop_table('usuario')
    op.drop_table('questao')
    op.drop_table('tipo_questao')
    op.drop_table('sexo')
    op.drop_table('objetivo')
    op.drop_table('idioma')
    op.drop_table('experiencia_idioma')
    op.drop_table('disponibilidade')
    # ### end Alembic commands ###
