"""Carga na tabela questoes

Revision ID: 9130aa390f30
Revises: 49caa065793f
Create Date: 2025-11-24 09:53:01.058927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9130aa390f30'
down_revision: Union[str, Sequence[str], None] = '49caa065793f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is _ type of chess in which _ chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["decoration", "a", "release", "postal", "motivated"]', 'a');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Talking _____ murder before a body is found is quite weird.','["elaborate", "about", "aborigine", "collaborator", "collaborative"]', 'about');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A Federal Reserve director has been fired in an unprecedented move, but will seek legal ______ to remain in her position.','["practicality", "exactly", "action", "contract", "manufacture"]', 'action');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '_____ a storm comes a calm.','["overdraft", "antiaircraft", "craft", "after", "aircraft"]', 'after');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live _____; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["coverage", "shortage", "tragic", "again", "drag"]', 'again');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep ___ the positions of the game exclusively in his memory.','["idiomatically", "internal", "egalitarian", "spiral", "all"]', 'all');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Esteban is a man of superhuman height—______ a giant!','["palm", "calmly", "qualm", "calm", "almost"]', 'almost');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We need a little time _____.','["jealous", "alone", "catalog/catalogue", "jealously", "alongside"]', 'alone');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'If one has the right to live, then one should ____ have the right to die. If not, then living is not a right, but an obligation.','["rally", "balance", "proverbial", "also", "atypical"]', 'also');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I __ staying at a hotel in New York.','["flame", "trample", "camera", "am", "amazing"]', 'am');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'You need to have __ account to send a message.','["an", "disturbance", "instant", "tyranny", "assistance"]', 'an');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board ___ without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["mathematician", "and", "anywhere", "organism", "quantity"]', 'and');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I ate a hamburger and ordered _______.','["canon", "nano", "another", "maneuver/manoeuvre", "volcano"]', 'another');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making ___ written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["dancing", "vanity", "veteran", "assurance", "any"]', 'any');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '"Pakistan is going to be a very, very important country in the future and we want to be sure that we ___ part of that," he emphasised.','["arrival", "insular", "are", "prepare", "artist"]', 'are');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A fence runs ______ the house.','["around", "kangaroo", "barometer", "arouse", "baroque"]', 'around');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Life is a melody composed with supreme ___ and excellent mastery.','["harass", "clearness", "parasite", "unfamiliar", "art"]', 'art');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. __ we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["sarcastically", "gymnastics", "ashamed", "as", "enthusiastically"]', 'as');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'They just wanted to ___ me a few questions.','["basketball", "association", "hastily", "astonish", "ask"]', 'ask');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A strong wind blew __ night.','["accurately", "at", "ornate", "transformation", "humiliate"]', 'at');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I have known him since he was a ____.','["battered", "baker", "barrel", "bacon", "baby"]', 'baby');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''m getting a ___ feeling.','["basement", "backpacking", "bad", "urban", "barrier"]', 'bad');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Nobody can __ a head coach of a soccer team without being a soccer player.','["be", "believably", "deliberate", "fiber/fibre", "wardrobe"]', 'be');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Is it a ____?','["between", "September", "behalf", "cyberschool", "bear"]', 'bear');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I am getting fat _______ I eat a lot of sweets.','["below", "proscribe", "become", "prescribe", "because"]', 'because');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we ______ only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["besides", "because of", "barbecue", "number", "become"]', 'become');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Talking about murder ______ a body is found is quite weird.','["been", "unbeatable", "globe", "belt", "before"]', 'before');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The team placed food ______ a fence the chimpanzees could get if they worked together to pull two or three sets of levers.','["behavior/behaviour", "behest", "behalf", "behind", "behave"]', 'behind');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'It''s a secret _______ you and me.','["alphabetical", "better", "alphabet", "bet", "between"]', 'between');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Tomorrow''s a ___ day.','["mobile", "bitter", "biscuit", "profitability", "big"]', 'big');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'She is wearing a ____ dress.','["public", "blur", "accessible", "infallible", "blue"]', 'blue');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the _____ and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["board", "elaborate", "embodiment", "boast", "boat"]', 'board');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Talking about murder before a ____ is found is quite weird.','["box", "mailbox", "walkabout", "bomber", "body"]', 'body');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A friend lent me that ____.','["keyboard", "bonus", "book", "bookcase", "boxing"]', 'book');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The competitors ____ took medical timeouts in their final, grueling match on a sweltering summer day.','["snowboarding", "bombing", "both", "boy", "borrow"]', 'both');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The ___ was speechless when talking to a girl.','["symbol", "bore", "boy", "bottom", "board"]', 'boy');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, ___ when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["distributor", "butterfly", "building", "abundance", "but"]', 'but');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I need to ___ a few things at the mall. Do you want to come with me?','["bureaucratic", "bulk", "buy", "builder", "bulb"]', 'buy');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The term "arduous march" was used __ the authoritarian regime to describe a famine that killed millions of people in the 1990s.','["lobby", "bypass", "by", "babysitter", "hobby"]', 'by');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Nobody ___ be a head coach of a soccer team without being a soccer player.','["can", "volcano", "calorific", "impressionistically", "clerical"]', 'can');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'You''ve got a ___, right?','["car", "delicacy", "fantastically", "calamity", "critical"]', 'car');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Have you ever been a witness in a court ____?','["calf", "scandal", "numerical", "case", "so-called"]', 'case');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Stop acting like a spoilt _____.','["chip", "child", "psychiatrist", "mischief", "patchily"]', 'child');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Nobody can be a head _____ of a soccer team without being a soccer player.','["waistcoat", "coalition", "coach", "coastline", "coarse"]', 'coach');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I need to buy a few things at the mall. Do you want to ____ with me?','["continuously", "competition", "alcohol", "come", "coffee"]', 'come');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Mrs. Wood is a very good ____.','["coastal", "cook", "microscopy", "cold", "conditionally"]', 'cook');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The team placed food behind a fence the chimpanzees _____ get if they worked together to pull two or three sets of levers.','["countless", "council", "account", "acoustics", "could"]', 'could');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been ___ off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["cut", "scuba", "obscure", "succulently", "spectacular"]', 'cut');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''m married and I have a ________.','["daunt", "daughter", "daze", "redundantly", "madame"]', 'daughter');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The competitors both took medical timeouts in their final, grueling match on a sweltering summer ___.','["danger", "Sunday", "day", "dawn", "modal verb/modal"]', 'day');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The term "arduous march" was used by the authoritarian regime to ________ a famine that killed millions of people in the 1990s.','["describe", "widespread", "pedestrian", "deserve", "descriptive"]', 'describe');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I want to __ tomorrow is to find a good part-time job.','["tremendously", "do", "doubtful", "document", "docilely"]', 'do');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''ll ____ a map for you.','["drive", "driver", "drop", "drown", "draw"]', 'draw');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'It isn''t a _____.','["dream", "dressed", "addressee", "undressed", "hundred"]', 'dream');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'She is wearing a blue _____.','["dreadful", "undreamed", "dream", "dread", "dress"]', 'dress');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ of us should plant a tree.','["sneak", "each", "teacher", "leading", "nearby"]', 'each');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I am getting fat because I ___ a lot of sweets.','["beagle", "eastern", "eat", "weather forecast", "pleasantly"]', 'eat');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Life is a melody composed with supreme art and _________ mastery.','["excel", "inexcusable", "excellent", "exception", "exclaim"]', 'excellent');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I am getting ___ because I eat a lot of sweets.','["infallibly", "fat", "faulty", "fairly", "farmland"]', 'fat');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'My ______ is a bit old-fashioned.','["fatality", "fate", "father", "fatal", "fat"]', 'father');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''m getting a bad _______.','["feedback", "feed", "feel", "feeling", "fee"]', 'feeling');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I want to do tomorrow is to ____ a good part-time job.','["finely", "find", "official", "bona fide", "emulsifier"]', 'find');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The _____ thing I want to do tomorrow is to find a good part-time job.','["confirm", "firm", "firmly", "first", "firearm"]', 'first');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The team placed ____ behind a fence the chimpanzees could get if they worked together to pull two or three sets of levers.','["four", "deforestation", "forbidden", "air force", "food"]', 'food');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Thanks a lot ___ having warned me!','["deforestation", "forfeit", "foolishly", "for", "informative"]', 'for');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A ______ lent me that book.','["refrigerator", "fright", "friend", "frighten", "frightened"]', 'friend');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'It''ll be a ___ weekend.','["insightfully", "suffuse", "functional", "fun", "forcefully"]', 'fun');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '"Pakistan is going to be a very, very important country in the ______ and we want to be sure that we are part of that," he emphasised.','["disdainful", "future", "refute", "helpful", "fully"]', 'future');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the ____ exclusively in his memory.','["gardening", "organic", "regain", "game", "gather"]', 'game');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Do you want me to ___ a doctor?','["refugee", "disparage", "get", "tiger", "belligerent"]', 'get');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The boy was speechless when talking to a ____.','["girl", "agile", "ecological", "disparagingly", "zoologist"]', 'girl');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I might ____ up soon and have a kip instead.','["encouraging", "ecologist", "psychological", "magic", "give"]', 'give');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I want to do tomorrow is to find a ____ part-time job.','["gorilla", "allegory", "gown", "good", "jargon"]', 'good');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'They paid his words a _____ deal of attention.','["progressive", "great", "regrettably", "aggressively", "degree"]', 'great');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the _____ seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["agreement", "agree", "green", "greet", "great"]', 'green');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'This is a Bible study _____.','["group", "ground floor", "underground", "ground", "growth"]', 'group');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'He is a plucky ___.','["gushing", "guy", "argue", "argument", "guard"]', 'guy');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We ___ a good time.','["emphasize/emphasize", "have to", "hairdryer", "orchard", "had"]', 'had');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I ate a _________ and ordered another.','["shameful", "shambles", "unashamedly", "ham", "hamburger"]', 'hamburger');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he ___ to keep all the positions of the game exclusively in his memory.','["hapless", "exhausting", "has", "handkerchief", "hastily"]', 'has');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and ____ not even a grave among those we love. We ____ not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, ____ souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["harmless", "shatter", "haunt", "have", "lethargy"]', 'have');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, __ has to keep all the positions of the game exclusively in his memory.','["central heating", "hey", "he", "therefore", "authenticity"]', 'he');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Nobody can be a ____ coach of a soccer team without being a soccer player.','["head", "heaven", "nowhere", "kitchen", "rhetorically"]', 'head');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Love is the only reality and it is not a mere sentiment. It is the ultimate truth that lies at the _____ of creation.','["heap", "cheap", "northeast", "heart", "heavily"]', 'heart');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I can''t do all of this without a little ____.','["cheeky", "sphere", "heifer", "help", "shed"]', 'help');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A Federal Reserve director has been fired in an unprecedented move, but will seek legal action to remain in ___ position.','["northern", "where", "her", "motherland", "chewing gum"]', 'her');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist ____, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["here", "heartwarming/heart-warming", "these", "schedule", "heavily"]', 'here');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I have known ___ since he was a baby.','["windshield", "chirp", "him", "chief", "nothing"]', 'him');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes ___ moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in ___ memory.','["hardship", "his", "fishing", "warship", "graphics"]', 'his');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I am staying at a _____ in New York.','["hot", "photocopy", "photographer", "shot", "hotel"]', 'hotel');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A fence runs around the _____.','["silhouette", "amorphous", "without", "house", "shoulder"]', 'house');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Will it ____ a lot?','["thumb", "hurt", "thus", "parachute", "chuckle"]', 'hurt');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing _ want to do tomorrow is to find a good part-time job.','["I", "ID card", "IT", "ID", "Internet/internet"]', 'I');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I don''t think that it is a good ____ to do that.','["video game", "idea", "side", "incident", "self-confidence"]', 'idea');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I think __ I talked more often with a native speaker, my English skills would improve quickly.','["horrify", "difficulty", "if", "midwife", "differ"]', 'if');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '"Pakistan is going to be a very, very _________ country in the future and we want to be sure that we are part of that," he emphasised.','["imp", "impulsive", "implication", "impersonator", "important"]', 'important');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess __ which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively __ his memory.','["in", "marginally", "instant", "misunderstanding", "parking"]', 'in');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess __ a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["is", "archaeologist/archeologist", "distant", "computerize/computerise", "whiskey/whisky"]', 'is');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '__ isn''t a dream.','["forfeiture", "tacitly", "uniformity", "architect", "it"]', 'it');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I want to do tomorrow is to find a good part-time ___.','["job", "disc jockey/disk jockey", "adjoin", "enjoy", "enjoyment"]', 'job');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'They ____ wanted to ask me a few questions.','["justly", "jump", "just", "jungle", "jug"]', 'just');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to ____ all the positions of the game exclusively in his memory.','["keep", "bake", "backpacker", "invoke", "sketch"]', 'keep');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I took piano lessons when I was a ___.','["cooking", "kid", "walking", "kitchen", "kindness"]', 'kid');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I put a _____ on the table.','["knife", "knit", "knowingly", "acknowledge", "weakness"]', 'knife');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A poet is the translator of the silent ________ of nature to the world.','["lane", "language", "landlady", "island", "melancholy"]', 'language');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ is a melody composed with supreme art and excellent mastery.','["novelist", "underline", "publisher", "life", "replica"]', 'life');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Stop acting ____ a spoilt child.','["timeliness", "like", "olive oil", "polite", "blight"]', 'like');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'All weapons and equipment used during combat are inspected before each battle, to ensure that they comply with a long ____ of safety regulations.','["feeling", "reptilian", "duplicate", "live", "list"]', 'list');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Can''t you stay a ______ longer?','["qualitative", "little", "politician", "hospitality", "profitability"]', 'little');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes ____ for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never ____ again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which ____ forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["qualification", "civilization/civilisation", "publicity", "live", "splinter"]', 'live');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''m ______ in a small town.','["olive", "sliver", "salivary", "delivery", "living"]', 'living');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'All weapons and equipment used during combat are inspected before each battle, to ensure that they comply with a ____ list of safety regulations.','["block", "meteorological", "blogger", "lovely", "long"]', 'long');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'He knows a ___ of people.','["anthology", "flood", "block", "loud", "lot"]', 'lot');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we ____. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["glove", "love", "float", "loud", "ecologically"]', 'love');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I__ living in a small town.','["''re", "''m", "o''clock", "driver''s license/driving licence", "''s"]', '''m');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Esteban is a ___ of superhuman height—almost a giant!','["man", "maggot", "mailbox", "unmanned", "imaginary"]', 'man');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''ll draw a ___ for you.','["mankind", "remain", "fisherman", "map", "primarily"]', 'map');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The term "arduous _____" was used by the authoritarian regime to describe a famine that killed millions of people in the 1990s.','["MP3 player", "March", "Mrs./Mrs", "Mr./Mr", "a.m./A.M./am/AM"]', 'March');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The competitors both took medical timeouts in their final, grueling _____ on a sweltering summer day.','["match", "materialistic", "automatically", "maternal", "exclamation mark"]', 'match');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Thanks a lot for having warned __!','["someone", "fume", "me", "ephemerality", "melodiously"]', 'me');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his ______.','["memorable", "memory", "remember", "member", "membership"]', 'memory');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'You need to have an account to send a _______.','["mesmeric", "domestic", "domestication", "message", "messy"]', 'message');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish ____. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["morality", "good morning", "more", "most", "mourn"]', 'more');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A Federal Reserve director has been fired in an unprecedented ____, but will seek legal action to remain in her position.','["moral", "chemotherapy", "motherland", "move", "mover"]', 'move');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I prefer going for a walk to seeing the _____.','["removed", "remove", "mover", "movie", "movement"]', 'movie');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '__ father is a bit old-fashioned.','["economy", "myriad", "my", "demystification", "clammy"]', 'my');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I ____ a new chainsaw.','["zone", "mountaineer", "need", "nine", "happiness"]', 'need');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall _____ live again; like the green seaweed when once it has been cut off, we can _____ flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall _____ see.','["never", "uneventful", "benevolent", "uneven", "benevolence"]', 'never');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I need a ___ chainsaw.','["constrained", "new", "stuffiness", "determine", "social networking"]', 'new');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A strong wind blew at _____.','["night", "vanity", "benignly", "benign", "nigh"]', 'night');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have ___ even a grave among those we love. We have ___ immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["not", "phenomenon", "knowledge", "snow", "honor/honour"]', 'not');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type __ chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions __ the game exclusively in his memory.','["of", "profound", "profession", "post office", "out of"]', 'of');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut ___, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["offhand", "soft", "off", "profile", "waterproof"]', 'off');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I think if I talked more _____ with a native speaker, my English skills would improve quickly.','["soft drink", "software", "often", "soft", "softly"]', 'often');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'My father is a bit ___-fashioned.','["collaboration", "old", "wholly", "benevolent", "revolutionary"]', 'old');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I put a knife __ the table.','["recreation", "monotony", "on", "consequently", "receptionist"]', 'on');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when ____ it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["once", "self-confident", "illustration", "isolation", "oppression"]', 'once');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '___ hundred years is called a century.','["one", "comparison", "conference", "afternoon", "attention"]', 'one');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become ____ foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["decomposition", "tone", "afternoon", "only", "revolution"]', 'only');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The team placed food behind a fence the chimpanzees could get if they worked together to pull two __ three sets of levers.','["portrayal", "conformity", "morality", "vigor/vigour", "or"]', 'or');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise ___ of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["flavor/flavour", "thousand", "out", "out of", "throughout"]', 'out');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'He knows a lot of ______.','["people", "dependent", "third person", "permission", "penniless"]', 'people');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'He''s a very selfish ______.','["person", "upper", "perceptive", "experienced", "persistent"]', 'person');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I took _____ lessons when I was a kid.','["happily", "picky", "pillow", "piano", "Olympia"]', 'piano');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess ______ makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["player", "playmate", "applause", "replace", "complaint"]', 'player');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Take a deep breath, ______.','["complement", "please", "topple", "pleasing", "supple"]', 'please');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I ___ a knife on the table.','["punctual", "push", "put", "corpus", "compute"]', 'put');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I think if I talked more often with a native speaker, my English skills would improve _______.','["requisition", "tranquilize/tranquilise", "quickly", "colloquium", "quip"]', 'quickly');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Are you ______ a nun?','["firearm", "dread", "daydream", "undreamed", "really"]', 'really');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'My father runs a __________.','["restaurant", "forestry", "restore", "overestimate", "restrict"]', 'restaurant');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'You''ve got a car, _____?','["originally", "right", "trigger", "originate", "frigate"]', 'right');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Tomorrow__ a big day.','["driver''s license/driving licence", "o''clock", "''re", "''s", "''m"]', '''s');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never ___.','["see", "sew", "selfless", "researcher", "upset"]', 'see');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '___ needs to find a job.','["bookshelf", "eyelash", "refurbish", "apprenticeship", "she"]', 'she');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Each of us ______ plant a tree.','["shoal", "showbiz", "shortlist", "shop", "should"]', 'should');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''m living in a _____ town.','["spokesman", "classmate", "smart", "businessman", "small"]', 'small');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, __ do they rise to unknown and glorious regions which we shall never see.','["isolate", "son", "bothersome", "so", "blossom"]', 'so');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Nobody can be a head coach of a ______ team without being a ______ player.','["socialize/socialise", "society", "sociable", "social networking", "soccer"]', 'soccer');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I might give up ____ and have a kip instead.','["soon", "grandson", "source", "soccer", "adviser/advisor"]', 'soon');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I think you should _____ a bit more slowly.','["specimen", "disperse", "speak", "Shakespearean", "specially"]', 'speak');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Can''t you ____ a little longer?','["stay", "onstage", "constant", "psychiatrist", "boast"]', 'stay');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ acting like a spoilt child.','["mistake", "distillation", "stop", "accustom", "astonishing"]', 'stop');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A ______ wind blew at night.','["stressful", "apostrophe", "disastrous", "strong", "distribute"]', 'strong');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'This is a Bible _____ group.','["study", "stumble", "posture", "stultifyingly", "stuffily"]', 'study');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'He is proud of being a British _______.','["substitute", "subside", "subject", "substance", "substantiate"]', 'subject');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The competitors both took medical timeouts in their final, grueling match on a sweltering ______ day.','["summer", "consumer", "assumption", "resume", "assume"]', 'summer');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '"Pakistan is going to be a very, very important country in the future and we want to be ____ that we are part of that," he emphasised.','["sure", "persuade", "sunbeam", "sugar", "tracksuit"]', 'sure');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I put a knife on the _____.','["database", "uncomfortably", "establish", "marketability", "table"]', 'table');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ a deep breath, please.','["tantrum", "rudimentary", "take", "staple", "metaphor"]', 'take');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Nobody can be a head coach of a soccer ____ without being a soccer player.','["team", "monster", "liter/litre", "after", "unexpectedly"]', 'team');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '______ a lot for having warned me!','["lethargically", "thanks", "than", "toothache", "lethargy"]', 'thanks');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A friend lent me ____ book.','["thirst", "antithetical", "fifth", "wordsmith", "that"]', 'that');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing ___ board and without making any written record. Therefore, he has to keep all ___ positions of ___ game exclusively in his memory.','["anthropologically", "the", "forthcoming", "thin", "brother-in-law"]', 'the');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The competitors both took medical timeouts in _____ final, grueling match on a sweltering summer day.','["theme", "chemotherapy", "themselves", "their", "mathematical"]', 'their');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'If one has the right to live, ____ one should also have the right to die. If not, ____ living is not a right, but an obligation.','["thankful", "faithful", "then", "breathtaking", "though"]', 'then');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. ____ rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do ____ rise to unknown and glorious regions which we shall never see.','["they", "nonetheless", "thirst", "leather", "antithesis"]', 'they');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first _____ I want to do tomorrow is to find a good part-time job.','["ethic", "thickly", "thing", "ethical", "unthinkably"]', 'thing');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I don''t _____ that it is a good idea to do that.','["think", "unscathing", "thirty", "sympathize/sympathise", "thin"]', 'think');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ is a joke.','["toothbrush", "myth", "this", "the", "cloth"]', 'this');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among _____ we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["mythological", "mythology", "anthology", "those", "authority"]', 'those');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for _____ hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["anthropologist", "throat", "threatening", "three", "bathroom"]', 'three');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up _______ the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["threatening", "thread", "through", "threaten", "philanthropic"]', 'through');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I want to do tomorrow is to find a good part-____ job.','["protection", "connection/connexion", "time", "ingratiatingly", "beautifully"]', 'time');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has __ keep all the positions of the game exclusively in his memory.','["tourism", "tongue", "historic", "to", "stock"]', 'to');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The team placed food behind a fence the chimpanzees could get if they worked ________ to pull two or three sets of levers.','["photograph", "cinematographer", "photographer", "cinematography", "together"]', 'together');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I want to do ________ is to find a good part-time job.','["stomach", "symptomatic", "symptom", "tomorrow", "accustomed"]', 'tomorrow');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I''m living in a small ____.','["topple", "orator", "monotony", "town", "ton"]', 'town');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Each of us should plant a ____.','["portraiture", "treacherously", "tree", "trap", "stress"]', 'tree');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The team placed food behind a fence the chimpanzees could get if they worked together to pull ___ or three sets of levers.','["twist", "twitch", "notwithstanding", "two", "twisted"]', 'two');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a ____ of chess in which a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["type", "virtuosity", "commodity", "typically", "humanity"]', 'type');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise __ through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["presuppose", "roundup", "up", "superstition", "interruption"]', 'up');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Each of __ should plant a tree.','["venomously", "unenthusiastic", "superfluously", "amusing", "us"]', 'us');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Didn''t you ___ to have a car?','["customary", "blockbuster", "nervously", "rush hour", "use"]', 'use');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Mrs. Wood is a ____ good cook.','["dove", "leaven", "outlive", "very", "relieve"]', 'very');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ a while.','["straightforward", "wasteful", "walnut", "wares", "wait"]', 'wait');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I prefer going for a ____ to seeing the movie.','["wander", "warmly", "waste", "withdrawal", "walk"]', 'walk');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The first thing I ____ to do tomorrow is to find a good part-time job.','["southward", "silverware", "wristwatch", "want", "nowadays"]', 'want');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'The film ___ not a success in Japan.','["hardware", "was", "water", "washing-up", "wash"]', 'was');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but when we cease to exist here, we become only foam on the surface of the _____ and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed when once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the _____ and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["wristwatch", "awareness", "water", "washtub", "firewall"]', 'water');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I need to think of a ___ out.','["way", "motorway", "railway", "warmth", "upward"]', 'way');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '__ sometimes live for three hundred years, but when __ cease to exist here, __ become only foam on the surface of the water and have not even a grave among those __ love. __ have not immortal souls, __ shall never live again; like the green seaweed when once it has been cut off, __ can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As __ rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which __ shall never see.','["northwest", "weather forecast", "ewe", "we", "follower"]', 'we');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I come here at least three times a ____.','["week", "farewell", "chest of drawers", "weight", "wealth"]', 'week');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'It''ll be a fun _______.','["sweetheart", "between", "weekend", "interviewee", "weep"]', 'weekend');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'We sometimes live for three hundred years, but ____ we cease to exist here, we become only foam on the surface of the water and have not even a grave among those we love. We have not immortal souls, we shall never live again; like the green seaweed ____ once it has been cut off, we can never flourish more. Human beings, on the contrary, have souls which live forever, even after the body has been turned to dust. They rise up through the clear, pure air, beyond the glittering stars. As we rise out of the water and behold all the land of the earth, so do they rise to unknown and glorious regions which we shall never see.','["overwhelm", "when", "worthwhile", "everywhere", "where"]', 'when');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Blind chess is a type of chess in _____ a chess player makes his moves without seeing the board and without making any written record. Therefore, he has to keep all the positions of the game exclusively in his memory.','["worthwhile", "whir", "while", "which", "whilst"]', 'which');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '____ it hurt a lot?','["will", "unwise", "citywide", "owing", "witness"]', 'will');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'A strong ____ blew at night.','["wink", "will", "knowingly", "swimming", "wind"]', 'wind');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I think if I talked more often ____ a native speaker, my English skills would improve quickly.','["wipe", "wind", "wink", "swimming", "with"]', 'with');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, '''Philosophy'' is a Greek ____ that means the love of wisdom.','["worldwide", "housework", "word", "worm", "worship"]', 'word');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Experts addressing the _____ Economic Forum in New York are divided about the meaning of recent data showing a possible upturn in _____ economic growth.','["self-worth", "world", "wordsmith", "worn", "worm"]', 'world');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I think if I talked more often with a native speaker, my English skills _____ improve quickly.','["wound", "worker", "would", "two", "wonderful"]', 'would');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'I thought it was a comedown for the talented ______.','["rewrite", "write", "wristwatch", "writer", "playwright"]', 'writer');
    INSERT INTO public.questao (id_tipo_questao, nivel, caminho_arquivo, descricao_questao, json_opcao, resposta) VALUES (2, 1, NULL, 'Can''t ___ stay a little longer?','["youth", "your", "young", "you", "youthful"]', 'you');   
  """)
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
