"""Adição das tabelas Palavra e PalavraObjetivo

Revision ID: d0d6f28ff06b
Revises: 6c5a44b9c8ac
Create Date: 2025-10-09 20:18:54.334988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d6f28ff06b'
down_revision: Union[str, Sequence[str], None] = '6c5a44b9c8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palavra',
    sa.Column('id_palavra', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('descricao_palavra', sa.String(length=45), nullable=False),
    sa.Column('descricao_palavra_traducao', sa.String(length=45), nullable=True),
    sa.Column('CEFR', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id_palavra')
    )
    op.create_table('palavra_objetivo',
    sa.Column('id_palavra_objetivo', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('id_palavra', sa.Integer(), nullable=False),
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivo.id_objetivo'], ),
    sa.ForeignKeyConstraint(['id_palavra'], ['palavra.id_palavra'], ),
    sa.PrimaryKeyConstraint('id_palavra_objetivo')
    )
    op.add_column('data_acesso', sa.Column('id_usuario', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data_acesso', 'usuario', ['id_usuario'], ['id_usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_acesso', type_='foreignkey')
    op.drop_column('data_acesso', 'id_usuario')
    op.drop_table('palavra_objetivo')
    op.drop_table('palavra')
    # ### end Alembic commands ###
