"""Alteração na tabela Questao e QuestaoUsuario

Revision ID: d7f7348ab424
Revises: 5d801228bc1c
Create Date: 2025-10-14 09:32:06.945954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f7348ab424'
down_revision: Union[str, Sequence[str], None] = '5d801228bc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questao', sa.Column('descricao_questao', sa.String(length=100), nullable=False))
    op.add_column('questao', sa.Column('json_opcao', sa.String(length=100), nullable=True))
    op.add_column('questao', sa.Column('resposta', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('questao_id_objetivo_fkey'), 'questao', type_='foreignkey')
    op.drop_column('questao', 'json')
    op.drop_column('questao', 'id_objetivo')
    op.add_column('questao_usuario', sa.Column('data_resposta', sa.String(length=3), nullable=True))
    op.drop_column('questao_usuario', 'data_acerto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questao_usuario', sa.Column('data_acerto', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_column('questao_usuario', 'data_resposta')
    op.add_column('questao', sa.Column('id_objetivo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('questao', sa.Column('json', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('questao_id_objetivo_fkey'), 'questao', 'objetivo', ['id_objetivo'], ['id_objetivo'])
    op.drop_column('questao', 'resposta')
    op.drop_column('questao', 'json_opcao')
    op.drop_column('questao', 'descricao_questao')
    # ### end Alembic commands ###
