"""correção da estrutura da tabela questao e questao_usuario

Revision ID: ded343944172
Revises: 573471b019bd
Create Date: 2025-11-22 16:51:23.987404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded343944172'
down_revision: Union[str, Sequence[str], None] = '573471b019bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questao', 'descricao_questao',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('questao', 'json_opcao',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('questao_usuario', sa.Column('id_questao_usuario', sa.Integer(), sa.Identity(always=False, start=1), nullable=False))
    op.drop_column('questao_usuario', 'id_questaousuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questao_usuario', sa.Column('id_questaousuario', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False))
    op.drop_column('questao_usuario', 'id_questao_usuario')
    op.alter_column('questao', 'json_opcao',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('questao', 'descricao_questao',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
